---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
  namespace: envoy-gateway-system
spec:
  releaseName: envoy-gateway-crds
  chart:
    spec:
      chart: gateway-crds-helm
      sourceRef:
        kind: OCIRepository
        name: envoy-gateway-crds
        namespace: envoy-gateway-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    crds:
      gatewayAPI:
        enabled: true
        channel: experimental  # Includes TCPRoute, BackendTLSPolicy and other alpha resources
      envoyGateway:
        enabled: true
